{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name:  {{ .Chart.Name }}
    helm.sh/chart: {{ print $.Chart.Name "-" $.Chart.Version }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.certificate.clusterIssuer }}
  {{- $dnsName := pluck (.Values.global.env | default "default") .Values.certificate.dnsName | first }}
  commonName: {{ $dnsName }}
  dnsNames:
   - {{ $dnsName }}
{{- end }}