apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Chart.Name }}-buy
  labels:
    app.kubernetes.io/name:  {{ .Chart.Name }}
    helm.sh/chart: {{ print $.Chart.Name "-" $.Chart.Version }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- $env := .Values.global.env }}
  GLOBAL_ENVIRONMENT: "{{ $env }}"
  {{- range $k, $v := .Values.configMapBuy }}
    {{- if eq (kindOf $v) "map" }}
  {{ $k }}: "{{ pluck $env $v | default (pluck "default" $v) | first | default "" | toString | replace "{env}" $env }}"
    {{- else }}
  {{ $k }}: {{ $v | default "" | replace "{env}" $env | quote | indent 4 }}
    {{- end }}
  {{- end }}
